Resolves #10. Also patches bug (workflow dispatch app must be public, which enables user error on account installation, so added installation account verification as well)

diff --git a/backend-workflows/workflow-util/handlers/accept-assignment b/backend-workflows/workflow-util/handlers/accept-assignment
--- a/backend-workflows/workflow-util/handlers/accept-assignment
+++ b/backend-workflows/workflow-util/handlers/accept-assignment
@@ -48,6 +48,7 @@ then
 fi
 
 export STUDENT_USERNAME=$(cat curl.json | jq -r '.login')
+AUTHENTICATED_STUDENT_ID=$(cat curl.json | jq -r '.id')
 rm -f curl.json
 STUDENT_ASSIGNMENT_REPO="${ASSIGNMENT_NAME}-${STUDENT_USERNAME}"
 # Replace forbidden characters with hyphens
@@ -170,13 +171,59 @@ get_collaborator_status=$(curl -s -o /dev/null -w "%{http_code}" -L \
     "https://api.github.com/repos/${STUDENT_ASSIGNMENT_ORGANIZATION}/${STUDENT_ASSIGNMENT_REPO}/collaborators/$STUDENT_USERNAME")
 if [[ "$get_collaborator_status" == "404" ]]
 then
-    # User is not a collaborator. Add them.
+    # User is not a collaborator. We may need to add them, but first we have
+    # to check if this repo was previously created and registered under a
+    # different student's ID.
+    # Get STUDENT_ID repository variable if it exists
+    get_student_id_status=$(curl -s -o curl.json -w "%{http_code}" -L \
+        -H "Accept: application/vnd.github+json" \
+        -H "Authorization: Bearer ${assignment_creation_app_installation_access_token}" \
+        -H "X-GitHub-Api-Version: 2026-03-10" \
+        "https://api.github.com/repos/${STUDENT_ASSIGNMENT_ORGANIZATION}/${STUDENT_ASSIGNMENT_REPO}/actions/variables/STUDENT_ID")
+    if [[ "$get_student_id_status" == 200 ]]
+    then
+        # Extract variable value from curl.json
+        STUDENT_ID=$(cat curl.json | jq -r '.value')
+    else
+        # Variable doesn't exist. Then the repo can be registered to this
+	# student. Create
+        # the STUDENT_ID variable using ID of current authenticated
+        # user.
+        STUDENT_ID="$AUTHENTICATED_STUDENT_ID"
+        create_student_id_status=$(curl -s -o /dev/null -w "%{http_code}" -L \
+            -X POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "Authorization: Bearer ${assignment_creation_app_installation_access_token}" \
+            -H "X-GitHub-Api-Version: 2026-03-10" \
+            "https://api.github.com/repos/${STUDENT_ASSIGNMENT_ORGANIZATION}/${STUDENT_ASSIGNMENT_REPO}/actions/variables" \
+            -d '{"name":"STUDENT_ID","value":"'"$AUTHENTICATED_STUDENT_ID"'"}')
+        if [[ "$create_student_id_status" != 201 ]]
+        then
+            # Failed to create repo variable.
+            echo "Error: Got HTTP status $create_student_id_status when creating STUDENT_ID repository variable" >&2
+            exit 1
+        fi
+    fi
+    
+    # Verify that current authenticated user's ID matches that of student
+    # registered for repository
+    if [[ "$STUDENT_ID" != "$AUTHENTICATED_STUDENT_ID" ]]
+    then
+        # Wrong student. Should only happen if students' GitHub usernames
+        # change, so two students have the same username throughout the
+        # duration of a classroom's use. This repo was previously registered
+        # to a different student with this username.
+        # Fail with duplicate-username. Requires instructor to intervene
+        # and rename the old duplicate repository to something else.
+        echo "Error: Failed authentication when retrieving user information" >&2
+        echo -n '{"status": "duplicate-username"}' > result/status.json
+        exit 0
+    fi
+    
     # Send invite to add student as outside collaborator for repo, or add
     # as collaborator directly under certain conditions (e.g., if they're
     # a member of the organization, or a member of a team that's already
     # a collaborator)
-    echo here 1
-
     add_collaborator_status=$(curl -L \
         -s -o /dev/null -w "%{http_code}" \
         -X PUT \
